### ISSUE TITLE
Suggestion: Make a way to manually add & remove items from an ember bore

### ISSUE THREAD

**Issue by Ayrrow** [RootsTeam/Embers#12]
I appreciate that machine accessors and the cores are designed to be added to the bore, but its a bit overkill for the first step of the mod to require this & pipes.

**Comment by TheCorruption** [comment]
You will need to craft pipes at least once in the mod anyway, and its really easy to get them, also this would be strange since it would only be for this machine.

**Comment by Ayrrow** [comment]
Well I think my suggestion could extend to all machines. At the moment it seems silly that you craft the 'machine' then you craft the access block, then you've got to craft +2 inputs/outputs. Given that the pipes require lead plates, which are quite expensive early game (as they should be) **just** to build the generator seems to be a bit much; I mean you're going to want to automate it with pipes pretty quickly, its just annoying that you need them to actually use the bore itself. 

obviously this is only relevant if you're using the mod by itself (ie with no other pipe or ore duplication mods)/

**Comment by TheCorruption** [comment]
Lead plates are expensive early game because this isn't an early game mod, you can also use hoppers if you somehow can't find 7 lead ingots, adding this would make pipes unnecessary, and that's a problem considering its how you will spend most of your lead, also since this mod is going for no GUIs this will be either too complicated for simply retrieving items or annoying whenever you right-click on a machine by accident.

**Comment by Ayrrow** [comment]
Well it is a pretty early game mod - at least the ember collection and 2x ore processing. The only thing that is stopping me from actually playing the thing is the lead plates to extract the ember for the bore. I don't see why I need to use pipes to achieve this.

**Comment by TheCorruption** [comment]
Personally, I don't see 2x ore processing as an early game mechanic at all, but everyone has their own opinions on it, also you don't actually need to use pipes to use the machine, just some kind of block that transports items, like a hopper.

**Comment by Ayrrow** [comment]
You need pipes to extract the ember crystals I believe.

**Comment by elucent** [comment]
You do, and this is somewhat intentional. I want the mod to be just a little bit steep to get into -- not to the point that it's especially *hard* to do so, but if you want to get into the mod early-game it should be a conscious choice. Plus, it forces people to learn how the Embers pipe system works, which is very useful since the fluid pipes and (to a degree) the Ember emitter/receiver function the same way.
