### ISSUE TITLE
Plate Oredict "exploit"

### ISSUE THREAD

**Issue by lilmoefow** [RootsTeam/Embers#13]
All your crafting recipes use <ore:plateIron>, which would not be a problem if your plate crafting recipe were not 4 ingots to 1 plate.  Where as all other mods that add Iron plates are 1 to 1.   If Embers is played alone this is not a problem, but when played with other mods, your "prefered" method of crafting plates will never be used.   

Wanted to get your thoughts on that.

**Comment by elucent** [comment]
Eh, I don't mind. Not all other mods have iron plate recipes that are 1:1, back in 1.7.10 I remember quite a few had a 3:2 ratio of ingots to plates. I wanted to make it so that there's a pressing (pardon the pun) incentive to make the Stamper, and I think within Embers I do that quite well. If a user decides to add in a mod that undercuts this, it's not destabilizing my progression very much, and it's their decision. I'd rather not balance around other mods too specifically.
