### ISSUE TITLE
Issue with embers particles connecting

### ISSUE THREAD

**Issue by kyle-mathis** [RootsTeam/Embers#162]
I have no idea why but for some reason the particles shooting out of an emitter don't go to the receivers or relays, they just fly in a straight line. Yet the ember still transmits even though the particles don't go there. Tried to see if this is even you mods problem or just a mod conflict on Reddit but everyone on the FTB sub kept bitching I need to tell you and not waste there time, if its not your problem you can just delete this xD

Using FTB beyond 1.4.1

**Comment by ruyanve** [comment]
He is using embers-0.104 for 1.10.2, Forge version is unknown.
I think he is talking about this: https://youtu.be/yTc5olZODFQ?t=5m31s
Since Elucent is in the video I guess this is known.
He also mentioned he tested with and without Optifine without any change in outcome.

Also I wasn't "bitching", I was merely suggesting to report bugs to the issue tracker and not to a place where bug reports are not supposed to go.
Thank you!

**Comment by elucent** [comment]
This appears to either be a Sponge error or a bug with 1.10.2 Embers. I can't control Sponge, and I don't update 1.10.2 Embers anymore, so it's in a won't/can't fix situation.

**Comment by ruyanve** [comment]
I doubt is is a sponge issue, as the user has not mentioned multiplayer. Anyway, thanks for your reply!

**Comment by kyle-mathis** [comment]
It is a sponge issue, just tried it without and sponge and everything worked fine. Thanks for the reply Elucent.

And I do have sponge to write/test test things that could possibly go into multiplayer.

**Comment by ruyanve** [comment]
My bad then, good this has been cleared up.
