### ISSUE TITLE
[Suggestions/Improvements/maybe bug?] Heat system

### ISSUE THREAD

**Issue by MasterFee** [RootsTeam/Embers#173]
I love your mods they are unique and are awesome to play with. 
So first of all when you try to remove the augments the you'll get the tool with all its heat, the augments themselves and the Ancient Motive Core. Afterwards you are still able to augment the tool but with no sign on the tooltip and no Ancient Motive Core. Removing the augments after that still works.
Then I was wondering why one should put more Superheater on one tool (pickaxe), maybe you could add a chance to double the smelted ores after you reach a level (2 for 25% chance to double, 3 for 50%, 4 for 75 and 5 for 100%). 
The blasting augment level 1 has no effect on tools. Only with higher levels you can see an effect. By the way the blasting upgrade is able the destroy Bedrock.
I can't seem to find any way to collect heat for armor. Is it even possible? I tried taking damage from mobs, falling damage, swimming in lava, standing in fire and explosions but none of that got me any heat. Might be a bug or you didn't include it yet.
Finally I would be really looking forward on seeing augments that increase mining speed or mining level and stuff like that. Right now there are 6 augments for armor and weapons, whereas there are only 5 (3 particular useful: Superheater, Resonating Bell, Intelligent Apparatus) for tools.

**Comment by GeekBeam** [comment]
one the first point, I like the idea, it's not too bad, I'm just curious what method you would propose for removing said augments.
Super heater on tools is an autosmelt, which isn't very powerful, more on why that is on the last point.
blasting is more effective on weapons in particular, causing an AOE style damage.
the inability to gain heat on Armor is a bug all it's own, I would suggest submitting it as it's own issue, so that it can be addressed directly, I can confirm that I am also unable to gain any heat on armor, and this is after letting mobs hit and kill my character several times in two different packs.

on the point of more augments: I have been told that there will be far more progression within the mod, and that the augments at current are not very powerful for that reason. they are to be gated behind progression mechanics.

**Comment by GeekBeam** [comment]
I just found the method of removing augments. it is the same as putting them on.

you put item on anvil. smack it with hammer until the augment pops off. this can be done with the autohammer.

**Comment by MasterFee** [comment]
Well I'm aware of that method but my problem is that the Ancient Motive Core is removed too an therefore the heat system should be removed as well which isn't the case. To put the augments back on you have to add the Core first otherwise the Augments won't appear and won't work.

**Comment by elucent** [comment]
Fixed the armor heat bug, and the Ancient Motive Core can no longer be reclaimed.
