### ISSUE TITLE
[1.10.2] Extreme bandwidth use on dedicated server

### ISSUE THREAD

**Issue by Baughn** [RootsTeam/Embers#215]
I noticed my dedicated server is sitting at ~1MB/s per player online, which of course is too much for some of the players to handle at all. Using TickProfiler to look at the packets served, the result is -- well --

```
                 Packet | Count |    Size
                 embers | 77322 |  11.9MB
       SPacketChunkData |    86 |   2.7MB
             arsmagica2 | 10800 |   1.2MB
SPacketUpdateTileEntity |  3061 | 451.8KB
            theoneprobe |   648 | 199.5KB
```

I know you don't support 1.10.2 anymore, but this is rendering the game entirely unplayable. Is there anything I can do?

**Comment by elucent** [comment]
Remove Embers?

**Comment by Baughn** [comment]
As you wish. It's a pity, it seemed like a nice concept.

**Comment by elucent** [comment]
The 1.10 version is pretty darn buggy. I was initially not expecting it to be added to any modpacks, but FTB thought otherwise. :P

If I haven't frightened you away, maybe check back on the mod in 1.11 or 1.12? It should be better then. The 1.10 version also doesn't really offer a whole lot of content.

**Comment by Baughn** [comment]
Sorry, I'm not going to do that. I only play long-term worlds, and since you drop bugfix support for old versions, that makes your mods ineligible.
