### ISSUE TITLE
Looking at the todo list, several things look amazing.

### ISSUE THREAD

**Issue by KingEdward9830** [RootsTeam/Embers#230]
Core Fragment stuff sounds like a really cool endgame, and those automatons sound awesome too. I understand that with the update to 1.12 bugfixes are probably taking the highest spot on the priority list right now(and rightfully so), but next time there's a big content update(not to rush it, take your time and make it worth the wait!) What do you think will be most likely to be added? Automatons? Core Fragments? Any number of other things on that list? Something totally new that's not even written down? Lol, I don't mean to sound rude. Just curious about where you're planning to go next, that's all.

**Comment by elucent** [comment]
The entire to do list is pretty much out of date. 1.12 bugfixes aren't taking the top priority at the moment either.

I have honestly no idea what might be added and at this point the idea of dropping modding altogether is still crossing my mind. Maybe if I ever have a reliable decision (which is unlikely) I'll add some response to this issue.

Closing because this isn't an issue. A place like twitter or my discord would be a much better way to ask questions like this.

**Comment by KingEdward9830** [comment]
Sorry to hear that, but thanks for this mod and Roots.
