### ISSUE TITLE
Ember gauges not displaying proper numbers on a dedicated server

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Embers#36]
I'll have my machines suck my copper cell completely dry to the point where it cannot distribute any more ember to my machines, but the gauge on the cell(and on the ember activator) says they're both full of ember. When I put more ember crystals into the activator(providing more ember to the system), it begins to work again.

Basically my gauges keep telling me my machines/storage objects are full when they're most certainly not.

**Comment by AnZaNaMa** [comment]
I have also noticed this, on the ember activator. I would guess it's because there is some sort of client-server de-sync issue. I thought this, because breaking and replacing the gauge didn't fix the problem, but re-logging did. I looked in your code and it seems you're calling `markDirty()` on the block the emitter is attached to whenever the ember emitter updates.

Here's where it gets really strange: if the activator is completely empty and I put one ember crystal into it, the gauge updates for the first few hundred or so ember, but then stops. The number it stops updating the gauge at is not any specific number and if I put in shards one at a time, the number changes to show the amount in the emitter when the shard is consumed, but does not change when the emitter sends ember packets. Also, there does not seem to be any threshold above which it works correctly, using shards.

It's probably not relevant, but I tried moving the gauge to a different side of the block and that didn't fix it either. I would guess this means it's almost definitely a problem with the ember activator, not the gauge. I noticed you never call `markBlockForUpdate()` anywhere in your code for this specific area. Pretty sure this is only for updating rendering? Not completely sure, but I usually see it alongside `markDirty()` 

Also, on a completely unrelated note, I absolutely love the aesthetics and mechanics in this mod, as well as your code. It's the most human friendly java I've ever seen and I reference Roots and Embers all the time when I need help figuring out how a specific forge mechanic works. I praise you for this because almost every other developer out there (especially minecraft modders) doesn't ever bother to make their code cleanly organized, and it's probably a major factor it took so long for everyone to update to 1.8. Yeah, there were a lot of changes to the way the code worked itself, but if they were able to look back at their code and figure out what they did before, they wouldn't have to completely rewrite their entire mod.

Sorry, I'm rambling. Basically I think your code is just as beautiful if not better than the mod in-game :)

**Comment by al132** [comment]
I think he's probably right. Something like [this](https://github.com/McJty/McJtyLib/blob/1.10/src/main/java/mcjty/lib/entity/GenericTileEntity.java#L47) is what i've been using in my mods.

**Comment by AnZaNaMa** [comment]
Ah, yes sorry. Changed from `markBlockForUpdate()` to `notifyBlockUpdate` in 1.9

Gonna fork it and try this to see if it works, cause I really like modding but I always get way overwhelmed when I try to make my own full-fledged mods.

**Comment by elucent** [comment]
I don't use notifyBlockUpdate() because it's extremely expensive. Whenever it's called, it not only syncs the TE data (what I would use it for), it also rebakes the entire chunk model (very processor-intensive operation, unnecessary for me). Instead, I use a homemade packet to sync TE data. It works, but there's a few places that don't seem to get updated, probably because I'm just missing a call. I'll be changing up dials in the next update so they work, probably by giving them a special request packet to ensure that their TE data is up-to-date.

**Comment by AnZaNaMa** [comment]
Oh alright. I just went in and changed it to use notifyBlockUpdate() and that fixed the problem, so I'd have to say you're right in that there is a call missing somewhere. Thanks for the quick response! Also, let me know if you guys over at RootsTeam need any help with development cause I love the mod and I'd be interested in helping make it.

**Comment by elucent** [comment]
Actually, it's funny you say that. I was considering making a post on /r/FTB about looking for new developers a few minutes ago, but I've been on the fence about it. If you want to talk about it further, we have a Discord: https://discordapp.com/invite/rCWpGTN. That's where most of our development conversations happen.

**Comment by AnZaNaMa** [comment]
Cool!

**Comment by ShaunDreclin** [comment]
Can confirm this bug. Playing on multiplayer server, ember gauge on my ember activator says it has lots of ember in it but when I relog it correctly updates to say it's empty. Embers v0.104 (All the mods expert mode modpack)

**Comment by elucent** [comment]
I added an additional data request packet to dials in v0.200. Should fix this bug in most cases.
