### ISSUE TITLE
[Suggestion] Combined pipes in one space like EnderIO

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#57]
This is the one feature from EnderIO that I wish most other mods would adopt. While I do think you should need to be careful what else is next to your pipes such as various inventories, I don't like having to take up all that extra space to run two types of pipes between two machines. There is absolutely no reason to force the use of extra space like that if it is possible to make the pipes occupy the same block space. Plus, it could look very cool, if done properly!

**Comment by elucent** [comment]
Not a huge fan, I'd argue that there _is_ a reason to take up extra space: it gives you another design constraint to work around. I think Ender IO gets a lot of popularity because of its extremely customizable pipes, and that's fine...for Ender IO, because that's what the mod is all about. For a very mechanically-designed mod like Embers, I'd rather have people think more about how they run pipes, and have more of a challenge fitting things in a compact space.

So this probably isn't in store for the mod, at least not right now: I have a lot of things to add, and another even-more-popular mod to develop, so even if I change my mind, I have a lot of things that are higher priority for me at the moment. Sorry! I just have limited time to develop.
