### ISSUE TITLE
Client Time out On Server Join

### ISSUE THREAD

**Issue by lilmoefow** [RootsTeam/Embers#8]
I pregened our map using Nucleus Essentials, and I am now not able to join the server.  

Fml-Client -  https://gist.github.com/lilmoefow/a1d6004f9eaf915115fa095529ce8011

Fml-Server - https://gist.github.com/lilmoefow/032653d7c7be79b481d784b3ccddd621  (its the only part of it that i actually have left but its the main error that occurs when player joins the server)

Disabling Embers allowed me to join the server again and continue on playing.

Forge 12.18.1.2092
embers-0.004.jar

I used Sponge and Nucleus to pregen the world, but the timeouts still occur with them disabled.

**Comment by Mysteryem** [comment]
My best guess on the issue at hand is that the client is erroneously trying to send packets that are meant to be sent from the server to clients.

I believe at least part of this issue lies at https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/EventManager.java#L105 due to the lack of a world.isRemote check

Causing an attempt to send a MessageEmberGeneration packet (which is only registered to be sent from the server to clients as per https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/network/PacketHandler.java). Plus I'm not sure the sendToAll(...) method even works from the client side.

**Comment by elucent** [comment]
Should be fixed now!

**Comment by lilmoefow** [comment]
Do you know if Embers will spawn in Aromas Mining Dimension? 

https://mods.curse.com/mc-mods/minecraft/aroma1997s-dimensional-world

Or is a world reset recomended to use this mod again on my server?

**Comment by elucent** [comment]
Embers *should* spawn in Aroma's Mining Dimension. It should also retroactively generate, due to the fact that it has its own storage system in the world data and will check a chunk whenever it is loaded. I'm not sure if it will, though, so the Aroma's Mining Dimension should be a decent backup, if you don't want to explore into new chunks.

**Comment by lilmoefow** [comment]
We Pregenerated our map with a world border, so there isn't really "new chunks" unless I extend the world border.   I am really interested in checking out Embers, it looks like it has alot of potential so I will be re adding it to our server next time i update the pack.   

Will let you know how that works out ;)

**Comment by elucent** [comment]
Well, even without new chunks, it might still spawn, I haven't checked.

**Comment by lilmoefow** [comment]
That is one of the things that i will keep you posted on ;)
