### ISSUE TITLE
particals crashing game

### ISSUE THREAD

**Issue by theredghostwolf** [RootsTeam/Embers#95]
[crash-2017-01-20_19.00.30-client.txt](https://github.com/RootsTeam/Embers/files/720182/crash-2017-01-20_19.00.30-client.txt)

**Comment by elucent** [comment]
Can you give me any information regarding how you caused this error? What situation did it happen in?

**Comment by elucent** [comment]
^ clicked the wrong button. :P

**Comment by theredghostwolf** [comment]
not really unfortunately, i had a setup with 4 ember generators, outputting into a relay then going into a splitter to power my double smelter into stamper setup.

after which i left my game running and went for dinner onc ei came back i found that crashed with the report given above.

all i can think of that there were 8-16 fireballs on screen constantly and that over time it generated some crash.

**Comment by elucent** [comment]
Has it happened more than once?

**Comment by codewarrior0** [comment]
My server mate just got this crash with a nearly-identical traceback.

Here's my analysis:

`ParticleRenderer.particles` is a plain, non-synchronized ArrayList. The methods of `ParticleUtil` are used to add objects to this list. None of them have the possibility of adding a `null` to the list.

However, some callers of the `ParticleUtil` methods are the `Message*FX` classes under `network.message`. As of Forge for MC 1.8.9, network handlers are now run on the Netty I/O thread rather than the main server or client thread. I would suggest changing your message handlers to schedule the particle-add code on the main thread. 

I had to solve a similar problem with GregTech 5 for 1.10 regarding sound packets. Here is the commit to help you out:  https://github.com/Blood-Asp/GT5-Unofficial/pull/872/commits/210504462cefc104ce606377d4e6cc3ddf033aab.

**Comment by elucent** [comment]
I think this should be fixed now. I have null checks.
